### ISSUE TITLE
Segmentation fault on MultiFlex when processing a dictionary with duplicate semantic codes

### ISSUE THREAD

**Issue by martinec** [UnitexGramLab/unitex-core#1]
`MultiFlex` crashes when processing a dictionary that has a duplicate semantic code:

**What steps will reproduce the problem?**

`UnitexToolLogger MultiFlex Users/Lucie.Steible/Desktop/test.unitex.txt -oUsers/Lucie.Steible/Desktop/test.unitexflx.dic -aUsers/Lucie.Steible/Documents/Unitex-GramLab/Unitex/Alsatian/Alphabet.txt -dUsers/Lucie.Steible/Desktop/Seafile/RESTAURE/ressources/lexiques/DELA/test/Alsatian/Inflection -qutf8-no-bom`

**What is the expected output?**

`Done.`

**What do you see instead?**

```
In graph V6 label format incorrect in :P3s (at position 0):  '<'  expected.
Segmentation fault
```

**More info**

- DELAS entry:
  `üssrùtsche,V6+OLCA-automobile+inc+OLCA-automobile+inc+fr#glisser`

- Forum thread:
  https://groups.google.com/forum/#!topic/unitex-gramlab/2YFwZpaP3Ls

- Log file:
  https://groups.google.com/group/unitex-gramlab/attach/3dcfb12f25957/unitex_log_00000004.ulp?part=0.1&authuser=1

**Comment by hghwng** [comment]
Fixed in #5.
