### ISSUE TITLE
Failure of Compile and Flatten on large set of graphs

### ISSUE THREAD

**Issue by eric-laporte** [UnitexGramLab/unitex-core#126]
**Description**

'Compile & Flatten' fails on the attached set of graphs in Version 4.0alpha, whereas versions 3.1 to 3.3 used to work normally on this same set of graphs.
[V-tous.zip](https://github.com/UnitexGramLab/unitex-core/files/9188622/V-tous.zip)

**What steps will reproduce the problem?**

  1. Set Unitex in the Malagasy language
  2. Open V-tous.grf with the FSGraph menu
  3. Launch Tools > Compile & Flatten FST2, leaving the default option 'equivalent FST2 (subgraph calls may remain)'

**What is the expected output?**

The command should write an fst2 file and terminate normally.

**What do you see instead?**

The 'Working...' window seems to loop indefinitely during the computation of dependencies between subgraphs. Clicking on the Cancel button provokes a Java exception.

**More info**

- UnitexToolLogger version: 4.0alpha of September 9, 2021, compiled locally
- Did this work before?: [ x ] yes [ ] no

**Comment by martinec** [comment]
I'm unable to reproduce this on my setup (UnitexToolLogger version: 4.0alpha). Indeed, the compilation succeeded ([V-tous.fst2.zip](https://github.com/UnitexGramLab/unitex-core/files/9309863/V-tous.fst2.zip)).

- Grf2Fst2: finish with some warnings

```
Cannot open graph /data/devel/projects/UnitexGramLab/unitex-bugs/flatten/V-tous/a6vvGv.grf
WARNING: the graph 10 recognizes <E>
WARNING: the graph t2 recognizes <E>
WARNING: the graph F recognizes <E>
WARNING: the graph t6 recognizes <E>
WARNING: the graph t4 recognizes <E>
WARNING: the graph t3 recognizes <E>
WARNING: the graph zeroa recognizes <E>
WARNING: the graph ps1 recognizes <E>
WARNING: the graph ps5 recognizes <E>
WARNING: the graph ps6 recognizes <E>
WARNING: the graph ps7 recognizes <E>
WARNING: the graph 13 recognizes <E>
WARNING: the graph H recognizes <E>
WARNING: the graph 1 recognizes <E>
WARNING: the graph A recognizes <E>
WARNING: the graph 6 recognizes <E>
WARNING: the graph t7 recognizes <E>
WARNING: the graph 22 recognizes <E>
WARNING: the graph R recognizes <E>
WARNING: the graph 38 recognizes <E>
```

- Flatten: finish with no errors

Besides this, on my test, no fatal errors where reported on the core tools (Grf2Fst2, Flatten) or the Java IDE.

I could redo a test, but you must share an .ulp file.

**Comment by eric-laporte** [comment]
You're right. The command terminates normally after 30 s under Linux. I was too impatient to wait so long... Sorry for the inconvenience.
