### ISSUE TITLE
Incompatibility of morphological mode with recognition of sentence boundary

### ISSUE THREAD

**Issue by eric-laporte** [UnitexGramLab/unitex-core#20]
Presently, a part of a graph which is in the morphological mode cannot recognize the sentence boundary symbol '{S}' (example: the attached graph lim-phrase-mm.grf). A part of a graph which is not in the morphological mode can recognize this symbol (example: lim-phrase.grf). From the user's point of view, I can see no reason why this operation shouldn't be possible in the morphological mode too.
[lim-phrase-mm.grf.txt](https://github.com/UnitexGramLab/unitex-core/files/459668/lim-phrase-mm.grf.txt)
[lim-phrase.grf.txt](https://github.com/UnitexGramLab/unitex-core/files/459667/lim-phrase.grf.txt)

**Caution**
I am uploading the two graphs with a .txt extension (GitHub does not support GRF files). Please strip the .txt extension before using the graphs.

**What is the expected output?**
Apply lim-phrase-mm.grf to a text (Text > Locate Pattern). It should find occurrences of the pattern present in the text.

**Comment by martinec** [comment]
Thank you for your issue report. Actually, the sentence boundary symbol `{S}` is also recognized by the morphological mode:

![eos](https://cloud.githubusercontent.com/assets/800627/18385018/45d84352-768e-11e6-9544-5ada4e429828.png)

Concerning  `lim-phrase-mm.grf`, you are using a lexical mask `<V>` inside the morphological mode, hence, it's necessary to mark your dictionary as a  morphological mode one. For this, go to `Info > Preferences > Morphological-mode dictionaries` and select the dictionaries you want to use:

![eos1](https://cloud.githubusercontent.com/assets/800627/18385389/9fc87902-7690-11e6-90ac-4add2a26c67d.png)

 After this change, your example will works

![eos2](https://cloud.githubusercontent.com/assets/800627/18385394/a91ea454-7690-11e6-846f-cdc29fce3059.png)

**Comment by eric-laporte** [comment]
Sorry, really the problem with this example was that I had not declared the morphological-mode dictionary. And I did not exactly remember the problem I wanted to report (my Korean partners have mentioned it a few months ago). Now I open a new issue for it.
