### ISSUE TITLE
Incompatibility of morphological mode with recognition across sentence boundaries

### ISSUE THREAD

**Issue by eric-laporte** [UnitexGramLab/unitex-core#21]
(Sorry for my previous issue, it was mistaken)

Presently, a part of a graph which is in the morphological mode cannot recognize a text portion that spans through a sentence boundary symbol '{S}' (example: the attached graph lim-phrase-mm.grf). A part of a graph which is not in the morphological mode can recognize  a text portion that spans through this symbol (example: lim-phrase.grf). This operation makes sense in the morphological mode too.
[lim-phrase-mm.grf.txt](https://github.com/UnitexGramLab/unitex-core/files/464038/lim-phrase-mm.grf.txt)
[lim-phrase.grf.txt](https://github.com/UnitexGramLab/unitex-core/files/464039/lim-phrase.grf.txt)

Caution
I am uploading the two graphs with a .txt extension (GitHub does not support GRF files). Please strip the .txt extension before using the graphs.

What is the expected output?
Apply lim-phrase-mm.grf to a text (Text > Locate Pattern). It should find occurrences of the pattern present in the text.

**Comment by martinec** [comment]
Thank you for your issue report. In the morphological mode there is no implicit space between boxes (See the User's Manual, section 6.4.2). If you want to match the space before the sentence boundary symbol `{S}`, you have to make it explicit:

![eos3](https://cloud.githubusercontent.com/assets/800627/18406524/55ad9488-76fe-11e6-94f8-bf00f51318eb.png)

**Comment by eric-laporte** [comment]
Sorry, you are right again Cristian: the problem with this example was the space. I will rather ask the Korean team more details about the issue they mentioned.
