### ISSUE TITLE
Coding style mixed spaces and tabs

### ISSUE THREAD

**Issue by martinec** [UnitexGramLab/unitex-core#6]
The purpose of code indentation is readability. However, source code files have mixed spaces and tabs. This can quickly impact readability:

![screenshot](https://cloud.githubusercontent.com/assets/800627/14393618/26db9e8e-fdc8-11e5-9f9b-1aecafdb469b.png)

The aim of this issue is:

- Set default indentation to 2-spaces
- Fix any inconsistent indentation
- For those of us who prefer to use [tabs](http://c2.com/cgi/wiki?TabsVersusSpaces) to indent code, configure git to [automatically switch between spaces and tabs](http://stackoverflow.com/questions/2316677/can-git-automatically-switch-between-spaces-and-tabs/2318063#2318063)

**Comment by hghwng** [comment]
I guess `clang-format` is enough to handle all such things, including but not limited to the tab problem.

The main problem is to discuss an appropriate format.

**Comment by martinec** [comment]
I created a new branch called [`refactor/coding-style`](https://github.com/UnitexGramLab/unitex-core/tree/refactor/coding-style) including the next changes:

- Convert tabs into spaces : 1f194b36
- Trim trailing white spaces:  22470160
- add an `.editorconfig` file: 926eab31
- add a `.clang-format` file: af7e31c52  (thank you @hghwng for your suggestion)

For now, code  formatting style will only be applied to new source code files, i.e not for sources previous to the v3.2-alpha.

**Comment by hghwng** [comment]
I don't think simply converting tabs into spaces is enough. Tabs is not only used for aligning text in the beginning, but also in the middle. For example, see `Arabic.cpp` before and after conversion:

![Before](https://cloud.githubusercontent.com/assets/8509588/14663701/0ac2416c-06f6-11e6-845a-a60e12f23b9e.png)

![After](https://cloud.githubusercontent.com/assets/8509588/14663696/fd584530-06f5-11e6-8a85-a7bb3ecfe464.png)

**Comment by hghwng** [comment]
A more moderated version of space conversion. It converts all tabs to 4 spaces first, then replace 4 spaces *at the beginning of the line* with 2 spaces.

    find -name '*.cpp' -or -name '*.h' -exec bash -c "expand -t4 {} | sponge {}" \;
    find -name '*.cpp' -or -name '*.h' -exec sed -ri '/^ +/{s/    /  /g}' {} \;

**Comment by martinec** [comment]
`clang-format` versions prior to 3.8 ([rL254414](http://reviews.llvm.org/rL254414)) do not support the use of the `ReflowComments` directive. Let's take a comment from  `UnitexGetOpt.h` as example: 

![0c](https://cloud.githubusercontent.com/assets/800627/14672629/533c55d8-06f9-11e6-817f-aa406941e49b.png)

Without `ReflowComments: false` the output will be:

![1c](https://cloud.githubusercontent.com/assets/800627/14672701/bf27da38-06f9-11e6-9c55-8777d282fd94.png)

Having said that, as stated before, the general policy is no bulk reformatting the whole sources. *For now, code formatting style will only be applied to new files*.

**Comment by martinec** [comment]
Thank you @hghwng for your valuable feedback, you are right!  *simply converting tabs into spaces is not enough*. Therefore, changes from 1f194b36 will be rolled back.

Regarding your snippet for a *moderated version of space conversion*, I was doing some tests, but the results are still not suitable to overcome the mixed spaces and tabs issue.

Original code:

![0](https://cloud.githubusercontent.com/assets/800627/14673460/5e181fa0-06fe-11e6-9946-39eb8bd85a96.png)

Moderated version of space conversion:

![1](https://cloud.githubusercontent.com/assets/800627/14673477/71282be4-06fe-11e6-852c-ffa3da482928.png)

**Comment by hghwng** [comment]
> Having said that, as stated before, the general policy is no bulk reformatting the whole sources.

I'm sorry that I did't get your point. Could you please explain why it's better if we don't bulk reformat?

IMHO, *any* automated solution can't be perfect, due to the vague definition of "readability". However, with a comprehensive coding standard and an elaborated formatter, a basically acceptable effect can be achieved.

What if we automate the formatting, then verify and fine-turn the results by hand? Much less work is needed compared to manual formatting. Of course, it's better than any automated formatter.

**Comment by martinec** [comment]
> Could you please explain why it's better if we don't bulk reformat?

Besides that an automated approach is far to be perfect, any patch (bug fixes and enhancements) which depends on the previous code will be out-of-date. So what might seem like a *basically acceptable effect* could turn into a nightmare.

**Comment by martinec** [comment]
Commit 13b43b3 from @gvollant seems to achieve the desired effect regarding tabs to spaces conversion.

**Comment by hghwng** [comment]
@gvollant Could you please write down how to perfectly convert the tabs? I'm very interested in the details. Thank you!
