### ISSUE TITLE
Process variables in Explore graph paths

### ISSUE THREAD

**Issue by Eradan94** [UnitexGramLab/unitex-core#90]
**Is your feature request related to a problem? Please describe.**

Inputs, outputs and dictionary variables are not processed in "Explore graph paths".

**Describe the solution you'd like**

Most of the code is already is already existing in several files such as TransductionStack.cpp.
Reuse this code and continue the code of Issue #83 to process the variables.

**Comment by martinec** [comment]
The code introduced in v4.0-alpha to deal with this issue needs some rework:

https://github.com/UnitexGramLab/unitex-core/blob/86c3c77d78f1f4f8f271ecbd84849971715d0dc4/TransductionStack.cpp#L415
